routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/SGECECST', function () {
    return view('welcome');
});


Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home');

	Auth::routes();
	Route::group(['middleware' => 'auth'], function() {
    Route::get('gestion', function()
	{
   return view('gestion');
	});
 });	


Route::group(['middleware' => 'admin'], function() {
   	Route::resource('docentes','DocentesController');
   	Route::get('docentes/alta/{id}', [
      'uses'=> 'DocentesController@alta',
      'as'  => 'docentes.alta'
  ]);

	Route::resource('grados','GradosController');
	Route::resource('asignaciones','AsignacionesController');
	Route::resource('usuarios','UserController');
	
});
Route::group(['middleware' => 'auth'], function() {
	Route::resource('alumnos','AlumnosController');
	Route::get('alumnos/daraltas', [
      'uses'=> 'AlumnosController@daraltas',
      'as'  => 'alumnos.daraltas'
  ]);

	Route::resource('materias','MateriasController');
	Route::resource('examenes','ExamenesController');
	Route::get('examenes/modificar/{id}', [
      'uses'=> 'ExamenesController@modificar',
      'as'  => 'examenes.modificar'
  ]);
	Route::get('examenes/detalle/{id}', [
      'uses'=> 'ExamenesController@detalle',
      'as'  => 'examenes.detalle'
  ]);
	Route::get('examenes/materias/{id}', [
      'uses'=> 'ExamenesController@materias',
      'as'  => 'examenes.materias'
  ]);
	Route::resource('asignacionAlumnosGrados','AsignacionAlumnosGradosController');
	Route::resource('asignacionMateriasGrados','AsignacionMateriasGradosController');
	Route::resource('eventos','EventosController');
	Route::resource('asistencias','AsistenciasController');
	Route::get('asistencias/modificar/{id}', [
      'uses'=> 'AsistenciasController@modificar',
      'as'  => 'asistencias.modificar'
  ]);
	Route::get('asistencias/detalle/{id}', [
      'uses'=> 'AsistenciasController@detalle',
      'as'  => 'asistencias.detalle'
  ]);

	Route::resource('reportes','ReportesController');

});

resources/views/gestion.blade.php
@extends('layouts.app')

@section('content')
    <h3><small><i>Seleccione segun gestion</i></small></h3>
    @if (Auth::user()->usuario=='Administrador')
    <nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url('/gestion') }}">MENU</a>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Gestiones<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{{ route('docentes.index') }}">Gestión de Docentes </a></li>
          <li><a href="{{ route('alumnos.index') }}">Gestión de Estudiantes </a></li>
          <li><a href="{{ route('grados.index') }}">Gestión de Grados </a></li>
          <li><a href="{{ route('materias.index') }}">Gestión de Materias</a></li>
          <li><a href="{{ route('eventos.index') }}">Gestión de Eventos</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Asignaciones<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{{ route('asignaciones.index') }}">Grados y Docentes</a></li>
         <li><a href="{{ route('asignacionAlumnosGrados.index') }}">Alumnos y grados</a></li>
         <li><a href="{{ route('asignacionMateriasGrados.index') }}">Materias y grados</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="{{ route('usuarios.index') }}">Usuarios del Sistema</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="{{ url('/gestion') }}">Reportes</a></li>
    </ul>
   </div>
 </nav>
 @else
 <nav class="navbar navbar-default" role="navigation">
  <!-- El logotipo y el icono que despliega el menú se agrupan
       para mostrarlos mejor en los dispositivos móviles -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse"
            data-target=".navbar-ex1-collapse">
      <span class="sr-only">Desplegar navegación</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url('/gestion') }}">MENU</a>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Gestiones<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><a href="{{ route('alumnos.index') }}">Gestión de Estudiantes </a></li>
          <li><a href="{{ route('materias.index') }}">Gestión de Materias</a></li>
          <li><a href="{{ route('asistencias.index') }}">Gestión de Asistencias</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Asignaciones<b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
         <li><a href="{{ route('asignacionAlumnosGrados.index') }}">Alumnos y grados</a></li>
         <li><a href="{{ route('asignacionMateriasGrados.index') }}">Materias y grados</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="{{ route('examenes.index') }}">Evaluaciones</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="{{ route('eventos.index') }}">Eventos</a></li>
    </ul>
   </div>
 </nav>
 @endif
        <br>
            <div class="content">
                    <h3>BIENVENIDO / A <small> al Sistema de Gestión Escolar del Centro Escolar Católico Santo Tomás</small></h3>
                </div>
                <div class="text-center">
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <br>
                    <img src="{{URL::asset('/img/logo.png')}}" alt="profile Pic" height="100" width="100">
                    <h4><i>"Instruye al niño en el camino que debe andar, y aun cuando sea viejo no se apartará de él"</i><br> <small>Proverbios 22,6</small></h4>
                </div>
            </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">INGRESO</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if (Auth::user()->usuario=='Administrador')
                    Ingreso Correctamente como usuario Administrador!
                    @else
                    Ingreso Correctamente como usuario Docente!
                    @endif
                </div>
                <div class="text-center">
                        <a class="btn btn-primary" href="{{ url('/gestion') }}">Pagina Principal</a>
                </div>
                <br>
            </div>
        </div>
    </div>
   
@endsection