routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/SGECECST', function () {
    return view('welcome');
});


Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', 'HomeController@index')->name('home');

	Auth::routes();
	Route::group(['middleware' => 'auth'], function() {
    Route::get('gestion', function()
	{
   return view('gestion');
	});
 });	


Route::group(['middleware' => 'admin'], function() {
   	Route::resource('docentes','DocentesController');
   	Route::get('docentes/alta/{id}', [
      'uses'=> 'DocentesController@alta',
      'as'  => 'docentes.alta'
  ]);

	Route::resource('grados','GradosController');
	Route::resource('asignaciones','AsignacionesController');
	Route::resource('usuarios','UserController');
	
});
Route::group(['middleware' => 'auth'], function() {
	Route::resource('alumnos','AlumnosController');
	Route::get('alumnos/daraltas', [
      'uses'=> 'AlumnosController@daraltas',
      'as'  => 'alumnos.daraltas'
  ]);

	Route::resource('materias','MateriasController');
	Route::resource('examenes','ExamenesController');
	Route::get('examenes/modificar/{id}', [
      'uses'=> 'ExamenesController@modificar',
      'as'  => 'examenes.modificar'
  ]);
	Route::get('examenes/detalle/{id}', [
      'uses'=> 'ExamenesController@detalle',
      'as'  => 'examenes.detalle'
  ]);
	Route::get('examenes/materias/{id}', [
      'uses'=> 'ExamenesController@materias',
      'as'  => 'examenes.materias'
  ]);
	Route::resource('asignacionAlumnosGrados','AsignacionAlumnosGradosController');
	Route::resource('asignacionMateriasGrados','AsignacionMateriasGradosController');
	Route::resource('eventos','EventosController');
	Route::resource('asistencias','AsistenciasController');
	Route::get('asistencias/modificar/{id}', [
      'uses'=> 'AsistenciasController@modificar',
      'as'  => 'asistencias.modificar'
  ]);
	Route::get('asistencias/detalle/{id}', [
      'uses'=> 'AsistenciasController@detalle',
      'as'  => 'asistencias.detalle'
  ]);

	Route::resource('reportes','ReportesController');

});

app/Reportes.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reportes extends Model
{
    protected $fillable = ['id_asignaciones','id_asignacionAlumnosGrados','asignacionMateriasGrados','fecha','estado'];
    protected $dates = ['created_at','updated_at'];

    public function scopeNombre($query, $fecha)
	{
		return $query->where('fecha', 'LIKE', "%$fecha%");
	}

	public function asignaciones(){
    return $this->belongsTo('App\Asignaciones', 'id_asignaciones');
	}

	public function asignacionAlumnosGrados(){
    return $this->belongsTo('App\AsignacionAlumnosGrados', 'id_asignacionAlumnosGrados');
	}

	public function asignacionMateriasGrados(){
    return $this->belongsTo('App\AsignacionMateriasGrados', 'id_asignacionMateriasGrados');
	}
}

app/Http/Controllers/ReportesController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Examenes;
use App\Materias;
use App\Asignaciones;
use App\AsignacionAlumnosGrados;
use App\AsignacionMateriasGrados;
use PDF;

class ReportesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        $materias = Materias::all();
        $asignaciones = Asignaciones::all();
        $asignacionAlumnosGrados = AsignacionAlumnosGrados::all();
        $asignacionMateriasGrados = AsignacionMateriasGrados::all();
        $nombre =$request->get('nombre');
        $examenes = Examenes::orderBy('id','DESC')->nombre($nombre)->paginate(10);
        return view('reportes.index',compact('examenes','materias','asignaciones','asignacionAlumnosGrados','asignacionMateriasGrados'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {

      $materias = Materias::all();
        $asignacionAlumnosGrados = AsignacionAlumnosGrados::all();
      $examenes = Examenes::find($id);
      $view = view ('examenes.show',compact('examenes','materias','asignacionAlumnosGrados'));
      $pdf = \App::make('dompdf.wrapper');
      $pdf->loadHTML($view);
      return $pdf->stream('examenes.pdf');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {

    }

        public function grads()    {
        
        return view('reportes.grados');
    }

        public function alums()    {

    }
}
 

resources/views/Reportes/grads.blade.php
@extends('layouts.app')
@section('content')
<h1>hello world!</h1>
@endsection

resources/views/Reportes/index.blade.php
@extends ('layouts.app')
@section('content')
  <div class="row">
    <div class ="col-sm-12">
      <div class="full.right">
      <h2>REPORTES</h2>
      <br>
      </div>
    </div>
  </div>
  @if ($message = Session::get('success'))
      <div class="alert alert-success">
          <p>{{ $message }}</p>
      </div>
  @endif
      <br>
 <table class="table table-striped" style="text-align:center" >
    <tr>
      <th with="80px" style="text-align: center">No</th>
      <th  style="text-align: center">Nombre</th>
      <th  style="text-align: center">Accion</th>
          </tr>
    <?php $no=1; ?>
    @foreach ($asignaciones as $key => $value)
    <tr>
        <td>{{$no++}}</td>
        <td>{{ $value->Docentes->User->nombre }}</td>
        <td>{{ $value->Grados->nombre }}</td>
        <td>
          <a class="btn btn-info btn-lg" data-toggle="tooltip" data-placement="top" title="Detalles" href="{{route('materias.show',$value->id)}}">
              <i class="glyphicon glyphicon-list-alt"></i></a>
          <a class="btn btn-primary btn-lg" data-toggle="tooltip" data-placement="top" title="Editar" href="{{route('materias.edit',$value->id)}}">
              <i class="glyphicon glyphicon-pencil"></i></a>
            {!! Form::open(['method' => 'DELETE','route' => ['materias.destroy', $value->id],'style'=>'display:inline']) !!}
              <button type="submit" data-toggle="tooltip" data-placement="top" title="Eliminar" style="display: inline;" class="btn btn-danger btn-lg" onclick="return confirm('¿Esta seguro de eliminar este Registro?')"><i class="glyphicon glyphicon-trash" ></i></button>
            {!! Form::close() !!}
        </td>
      </tr>
    @endforeach
  </table>
  {!!$asignaciones->render()!!}
  <div class="text-center">
    <a class="btn btn-primary" href="{{ url('/gestion') }}">Regresar</a>
  </div>
@endsection